name: server

include:
  - path: ../network.yaml

services:
  portainer:
    image: portainer/portainer-ce:2.25.1-linux-arm-alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.home.local
      - VIRTUAL_PORT=9000
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_LOCATION}:/data
    networks:
      - intranet

volumes:
  portainer:
