version: '3.7'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.3.1-alpine
    restart: always
    container_name: nginx-proxy
    environment:
      - DHPARAM_SKIP=true
      - HTTPS_METHOD=redirect
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    networks:
      - intranet
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
