name: server

include:
  - path: ../../core/network.yaml

services:
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    image: backup:latest
    container_name: backup
    restart: no
    networks:
      - intranet
    volumes:
      - ${BACKUP_LOCATION}:/backups
      - ${LOG_FILE}:/backups.log
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
