name: server

include:
  - path: ../network.yaml

services:
  cloudflared:
    image: cloudflare/cloudflared:2024.12.2
    command: tunnel --loglevel error --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    container_name: cloudflared
    networks:
      - intranet
    restart: unless-stopped
    env_file:
      - .env
