name: server

include:
  - path: ../../core/network.yaml
  - path: ../../services/immich/docker-compose.yml

services:
  immich-album-creator-akshit-album:
    image: salvoxia/immich-folder-album-creator:latest
    container_name: immich-album-creator-akshit-album
    networks:
      - intranet
    env_file:
      - .env
    restart: no
    depends_on:
      - immich-server
    environment:
      API_URL: http://immich-server:2283/api/
      API_KEY: ${AKSHIT_API_KEY}
      ROOT_PATH: /usr/src/app/external/albums_akshit
      CRON_EXPRESSION: "0 2 * * *"
      MODE: "CREATE"
      UNATTENDED: 1
      SYNC_MODE: 2
      SET_ALBUM_THUMBNAIL: random
    entrypoint: /script/immich_auto_album.sh

  immich-album-creator-jiya-album:
    image: salvoxia/immich-folder-album-creator:latest
    container_name: immich-album-creator-jiya-album
    networks:
      - intranet
    env_file:
      - .env
    restart: no
    depends_on:
      - immich-server
    environment:
      API_URL: http://immich-server:2283/api/
      API_KEY: ${JIYA_API_KEY}
      ROOT_PATH: /usr/src/app/external/albums_jiya
      CRON_EXPRESSION: "0 2 * * *"
      MODE: "CREATE"
      UNATTENDED: 1
      SYNC_MODE: 2
      SET_ALBUM_THUMBNAIL: random
    entrypoint: /script/immich_auto_album.sh

  immich-album-creator-home-album:
    image: salvoxia/immich-folder-album-creator:latest
    container_name: immich-album-creator-home-album
    networks:
      - intranet
    env_file:
      - .env
    restart: no
    depends_on:
      - immich-server
    environment:
      API_URL: http://immich-server:2283/api/
      API_KEY: ${HOME_API_KEY}
      ROOT_PATH: /usr/src/app/external/albums
      CRON_EXPRESSION: "5 2 * * *"
      MODE: "CREATE"
      UNATTENDED: 1
      SYNC_MODE: 2
      SET_ALBUM_THUMBNAIL: random
    entrypoint: /script/immich_auto_album.sh

  immich-album-creator-akshit-pvt-album:
    image: salvoxia/immich-folder-album-creator:latest
    container_name: immich-album-creator-akshit-pvt-album
    networks:
      - intranet
    env_file:
      - .env
    restart: no
    depends_on:
      - pvt-immich-server
    environment:
      API_URL: http://pvt-immich-server:2283/api/
      API_KEY: ${AKSHIT_PVT_API_KEY}
      ROOT_PATH: /usr/src/app/external/albums
      CRON_EXPRESSION: "10 2 * * *"
      MODE: "CREATE"
      UNATTENDED: 1
      SYNC_MODE: 2
      SET_ALBUM_THUMBNAIL: random
    entrypoint: /script/immich_auto_album.sh
