name: server 

networks:
  intranet:
    name: intranet
    external: true
    driver: bridge

include:
  - path: portainer/docker-compose.yml    # 5000
  - path: nextcloud/docker-compose.yml    # 5001
  - path: immich/docker-compose.yml       # 5002
  - path: backups/docker-compose.yml      # 5003
  - path: jellyfin/docker-compose.yml     # 5004
  - path: pvt-immich/docker-compose.yml   # 6000
  - path: nginx/docker-compose.yml 
  - path: cloudflared/docker-compose.yml
  - path: netdata/docker-compose.yml