name: server 

networks:
  intranet:
    name: intranet
    external: true
    driver: bridge

include:
  - path: portainer/docker-compose.yml
  - path: nextcloud/docker-compose.yml
  # - path: photoprism/docker-compose.yml
  - path: immich/docker-compose.yml
  - path: nginx/docker-compose.yml
