version: "3.8"

services:
  immich-redis:
    image: redis:7.2.1-alpine3.18
    container_name: immich-redis
    networks:
      - intranet
    restart: always
  
  immich-postgres:
    image: postgres:16-alpine
    container_name: immich-postgres
    networks:
      - intranet
    env_file:
      - immich.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    volumes:
      - ${IMMICH_DATABASE_BASE_PATH}/postgres:/var/lib/postgresql/data
    restart: always

  immich-typesense:
    image: typesense/typesense:0.24.1@sha256:9bcff2b829f12074426ca044b56160ca9d777a0c488303469143dd9f8259d4dd
    container_name: immich-typesense
    networks:
      - intranet
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
      - TYPESENSE_DATA_DIR=/data
      # remove this to get debug messages
      - GLOG_minloglevel=1
    volumes:
      - ${IMMICH_DATABASE_BASE_PATH}/typesense:/data
    restart: always

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    volumes:
      - ${IMMICH_DATABASE_BASE_PATH}/model_cache:/cache
    env_file:
      - immich.env
    restart: always
    
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    networks:
      - intranet
    command: [ "start.sh", "immich" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - immich.env
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOSTNAME=${POSTGRES_HOSTNAME}
      - DB_USERNAME=${POSTGRES_USERNAME}
      - DB_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
    depends_on:
      - immich-redis
      - immich-postgres
      - immich-typesense
    restart: always

  immich-microservices:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-microservices
    networks:
      - intranet
    # extends:
    #   file: hwaccel.yml
    #   service: hwaccel
    command: [ "start.sh", "microservices" ]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
    env_file:
      - immich.env
    environment:
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOSTNAME=${POSTGRES_HOSTNAME}
      - DB_USERNAME=${POSTGRES_USERNAME}
      - DB_DATABASE_NAME=${POSTGRES_DATABASE_NAME}
    depends_on:
      - immich-redis
      - immich-postgres
      - immich-typesense

    restart: always

  immich-web:
    image: ghcr.io/immich-app/immich-web:${IMMICH_VERSION:-release}
    container_name: immich-web
    networks:
      - intranet
    env_file:
      - immich.env
    restart: always

  immich-proxy:
    image: ghcr.io/immich-app/immich-proxy:${IMMICH_VERSION:-release}
    container_name: immich-proxy
    networks:
      - intranet
    environment:
      # Make sure these values get passed through from the env file
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    depends_on:
      - immich-server
      - immich-web
    restart: always

volumes:
  immich-postgres:
  immich-machine-learning:
  immich-typesense:
