name: server

include:
  - path: ../../core/network.yaml

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Upload path
      - ${HOME_UPLOAD_LOCATION}:/usr/src/app/upload
      # Album Path
      - ${HOME_ARCHIVE_PATH}:/usr/src/app/external/archive
      - ${HOME_ALBUM_PATH}:/usr/src/app/external/albums
      - ${HOME_ALBUM_AKSHIT_PATH}:/usr/src/app/external/albums_akshit
      - ${HOME_ALBUM_JIYA_PATH}:/usr/src/app/external/albums_jiya
    environment:
      DB_USERNAME: ${HOME_DB_USERNAME}
      DB_DATABASE_NAME: ${HOME_DB_DATABASE_NAME}
      DB_PASSWORD: ${HOME_DB_PASSWORD}
      REDIS_DBINDEX: ${HOME_REDIS_DBINDEX}
    ports:
      - 2283:2283
    depends_on:
      - immich-redis
      - immich-database
    networks:
      - intranet
    restart: always
    healthcheck:
      disable: false

  pvt-immich-server:
    container_name: pvt_immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - .env
    environment:
      DB_USERNAME: ${PVT_DB_USERNAME}
      DB_DATABASE_NAME: ${PVT_DB_DATABASE_NAME}
      DB_PASSWORD: ${PVT_DB_PASSWORD}
      REDIS_DBINDEX: ${PVT_REDIS_DBINDEX}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # Upload Path
      - ${PVT_UPLOAD_LOCATION}:/usr/src/app/upload
      # Album Path
      - ${PVT_ALBUM_PATH}:/usr/src/app/external/vault
    ports:
      - 2200:2283
    depends_on:
      - immich-redis
      - immich-database
    networks:
      - intranet
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cuda # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - intranet
    restart: always
    healthcheck:
      disable: false

  immich-redis:
    container_name: immich_redis
    networks:
      - intranet
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  immich-database:
    container_name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    env_file:
      - .env
    environment:
      POSTGRES_MULTIPLE_DATABASES: "${HOME_DB_DATABASE_NAME},${HOME_DB_USERNAME},${HOME_DB_PASSWORD}: ${PVT_DB_DATABASE_NAME},${PVT_DB_USERNAME},${PVT_DB_PASSWORD}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    networks:
      - intranet
    healthcheck:
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
        Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart: always

volumes:
  model-cache:
