version: '3.7'

services:
  nginx:
    image: nginx:1.25.2-alpine
    container_name: nginx
    restart: always
    networks: 
      - intranet
    ports:
      - 8000:8000
      - 8080:8080
      - 9000:9000

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./configs:/etc/nginx/ssl/configs/
      - ./certs:/etc/nginx/ssl/certs/