name: nginx

services:
  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx
    restart: always
    networks: 
      - intranet
    ports:
      - 443:443
      - 80:80

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./configs:/etc/nginx/ssl/configs/
      - ./certs:/etc/nginx/ssl/certs/
