name: nginx

services:
  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx
    restart: always
    networks: 
      - intranet
    ports:
      - 443:443
      - 80:80
      - 8000:8000
    depends_on:
      - nextcloud
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-enabled:/etc/nginx/sites-enabled
      - ./configs:/etc/nginx/ssl/configs/
      - ./certs:/etc/nginx/ssl/certs/
      - ${NC_HTML_LOCATION}:/var/www/html:z,ro
      - ${NC_DATA_LOCATION}:/var/www/html/data:z,ro
    env_file:
      - .env

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   restart: always
  #   networks: 
  #     - intranet
  #   volumes:
  #     - ./letsencrypt:/etc/letsencrypt
  #     - ./certs:/etc/letsencrypt/live
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"