name: server

include:
  - path: ../../core/network.yaml


services:
  nextcloud-mariadb:
    image: mariadb:11.4.1-rc
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    networks:
      - intranet
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/mysql
      - ${BACKUP_LOCATION}:/backup
    env_file:
      - .env

  nextcloud-redis:
    image: redis:7.2.5-alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - intranet

  nextcloud:
    image: nextcloud:29.0.0-fpm
    container_name: nextcloud
    depends_on:
      - nextcloud-redis
      - nextcloud-mariadb
    networks:
      - intranet
    restart: always
    environment:
      - VIRTUAL_HOST=nextcloud.pi4.local
      - VIRTUAL_PORT=80
    volumes:
      - ${HTML_LOCATION}:/var/www/html:z
      - ${DATA_LOCATION}:/var/www/html/data:z
    env_file:
      - .env
