name: server

include:
  - path: ../../core/network.yaml

services:
  nextcloud:
    image: nextcloud:30.0-fpm
    container_name: nextcloud
    depends_on:
      - nextcloud-redis
      - nextcloud-mariadb
    networks:
      - intranet
    restart: always
    volumes:
      - ${HTML_LOCATION}:/var/www/html:z
      - ${DATA_LOCATION}:/var/www/html/data:z
    env_file:
      - .env
    environment:
      REDIS_HOST: nextcloud-redis
      MYSQL_HOST: nextcloud-mariadb
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}

  nextcloud-mariadb:
    image: mariadb:11.4.1-rc
    container_name: nextcloud-mariadb
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: always
    networks:
      - intranet
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/mysql
      - ${BACKUP_LOCATION}:/backup
    env_file:
      - .env

  nextcloud-redis:
    image: redis:7.2.5-alpine
    container_name: nextcloud-redis
    restart: always
    networks:
      - intranet

