name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.3
    container_name: jellyfin
    user: 999:999
    volumes:
      - ${MEDIA_LOCATION}:/media
    restart: 'unless-stopped'
    networks:
      - intranet
    env_file:
      - .env
    ports:
      - 8096:8096
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://examp
    # # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'