version: "3.7"

services:
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy:1.3-alpine
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - "/var/run/docker.sock:/tmp/docker.sock:ro"

  portainer:
    image: portainer/portainer-ce:linux-arm64-2.19.0
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    environment:
      - VIRTUAL_HOST=portainer.pi4.local,172.24.65.30
      - VIRTUAL_PORT=9000
    # ports:
    #   - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/hdd/deployments/portainer:/data

    networks:
      - intranet

volumes:
  portainer: