---
- name: Setup Ubuntu Server
  hosts:
    - pi5
  become: true

  tasks:
    - name: Install Basic Applications
      ansible.builtin.apt:
        name:
          - net-tools
          - htop
          - tree
        state: present
        update_cache: true

    - name: "Add Docker repository and install Docker"
      ansible.builtin.include_tasks: docker.ansible.yml

    - name: "Enable docker service"
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: restarted
        daemon_reload: true
