---
- name: Setup Ubuntu Server
  hosts: homeServer
  become: yes

  tasks:
    - name: Add Docker repository and install Docker
      include_tasks: docker.ansible.yml

    - name: Enable docker service
      systemd:
        name: docker
        enabled: yes
        state: restarted
        daemon_reload: yes

  handlers:
    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
